version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 10
  reviewers:
  - NdagiStanley
  labels:
  - ruby
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 10
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: flake8
    versions:
    - 3.8.4
    - 3.9.0
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: weekly
    time: "02:00"
  open-pull-requests-limit: 10
